### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by grangeway** [lunet-io/lunet#3]
Hi Alexandre, 

I just wanted to check with this project is currently in a working state in the branch that's committed to git. 

Have cloned from git, done a build in visual studio of the project in /src and took the following guess at building the docs (As a test):

```
E:\new\lunet\doc>..\src\Lunet\bin\Debug\net5.0\lunet.exe build
```

This then gave the following output - I can see some linux or relative paths, so happy to try and work out what's going on, but noticed that the absurl function (which seems to have been added in 0.4.1 appears to be missing), so i'm just wondering if i've missed a build step / plugin 

```
info: lunet[0] Site build started (environment: prod)
fail: lunet[1] In /blog/test.md(7,57):  /blog/test.md(7,57) : error : The function `absurl` was not found
fail: lunet[2] Unable to copy file [/mnt/e/new/lunet/doc/favicon.ico] to [/favicon.ico]. Reason: Access to the path 'C:\DumpStack.log' is denied.
fail: lunet[3] Unable to copy file [/mnt/e/new/lunet/doc/images/lunet.png] to [/images/lunet.png]. Reason: Access to the path 'C:\DumpStack.log' is denied.
fail: lunet[4] In /includes/head.sbn-html(5,3):  /includes/head.sbn-html(5,3) : error : Unexpected exception while loading the include `builtins/head.sbn-html` from path `/includes/builtins/head.sbn-html`. Could not find file `/includes/builtins/head.sbn-html`.
fail: lunet[4] In /includes/head.sbn-html(5,3):  /includes/head.sbn-html(5,3) : error : Unexpected exception while loading the include `builtins/head.sbn-html` from path `/includes/builtins/head.sbn-html`. Could not find file `/includes/builtins/head.sbn-html`.
fail: lunet[6] In /includes/head.sbn-html(5,3):  /includes/head.sbn-html(5,3) : error : Unexpected exception while loading the include `builtins/head.sbn-html` from path `/includes/builtins/head.sbn-html`. Could not find file `/includes/builtins/head.sbn-html`.
fail: lunet[5] In /includes/head.sbn-html(5,3):  /includes/head.sbn-html(5,3) : error : Unexpected exception while loading the include `builtins/head.sbn-html` from path `/includes/builtins/head.sbn-html`. Could not find file `/includes/builtins/head.sbn-html`.
fail: lunet[7] No layout found for content [/tags/develop/] with layout name [tags] and type [term] with extension `html`
fail: lunet[8] No layout found for content [/tags/git/] with layout name [tags] and type [term] with extension `html`
fail: lunet[9] No layout found for content [/tags/open/] with layout name [tags] and type [term] with extension `html`
fail: lunet[10] In /includes/head.sbn-html(5,3):  /includes/head.sbn-html(5,3) : error : Unexpected exception while loading the include `builtins/head.sbn-html` from path `/includes/builtins/head.sbn-html`. Could not find file `/includes/builtins/head.sbn-html`.
info: lunet[11] Site build finished in 357.2491ms. 13 files processed. 616 bytes written.
```

**Comment by xoofx** [comment]
Yeah, the doc folder in lunet is probably not up to date, forgot to update it for a while as I was more working on other site projects. You can probably try it on [kalk/site](https://github.com/xoofx/kalk/tree/master/site) instead...

**Comment by grangeway** [comment]
I'm guessing you your development work on .core on linux, the kalk/site seems to be in a loop at the moment:

![image](https://user-images.githubusercontent.com/434241/124813048-4f93be80-df5c-11eb-8e40-b84aa81bcb41.png)

I suspect this is going to be a linux<>windows / vs \ type  issue. Will play around for a bit longer.

**Comment by xoofx** [comment]
Weird, no, I'm only working from Windows... but I haven't checked the latest commit I made... maybe I messed up something while optimizing stuffs a few weeks ago

**Comment by xoofx** [comment]
Ok, just tried and indeed, a recent optimization broke it, as I haven't checked it carefully recently, I will try to have a look later this week

**Comment by xoofx** [comment]
wow, it seems completely broken

**Comment by grangeway** [comment]
cool not just me then - i'm guessing if I pop your may 31st commit off the top of the stack, I should be good? :)

**Comment by xoofx** [comment]
I'm gonna try and remove the commit from master, it's pretty bad filling the disk with garbage.

**Comment by xoofx** [comment]
Removed the commit from master. It should be fine now. Sorry for the trouble
